version: '3.6'
services:
  csv-table:
    image: ${DOCKER_REGISTRY}/csv-table:${DOCKER_IMAGE_TAG}
    build:
      context: ../../
      dockerfile: services/dy-csv-table/Dockerfile
      target: production
      labels:
        io.simcore.key: '{"key": "simcore/services/dynamic/csv-table"}'
        io.simcore.version: '{"version": "${DOCKER_IMAGE_TAG}"}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.name: '{"name": "CSV Table viewer"}'
        io.simcore.description: '{"description": "CSV Table viewer powered by [csv-to-html-table](https://github.com/derekeder/csv-to-html-table)"}'
        io.simcore.authors: '{"authors": [{"name": "odeimaiz", "email": "maiz@itis.swiss", "affiliation": "ITIS Foundation"}]}'
        io.simcore.contact: '{"contact": "maiz@itis.swiss"}'
        io.simcore.inputs: '{"inputs": {"input_1": {"label": "Input data", "displayOrder":
          0, "description": "Input data csv", "type": "data:text/csv", "fileToKeyMap":
          {"input.csv": "input_1"}}}}'
        io.simcore.outputs: '{"outputs": {"output_1": {"label": "Input data", "displayOrder":
          0, "description": "Input data csv", "type": "data:text/csv", "fileToKeyMap":
          {"input.csv": "output_1"}}}}'
        simcore.service.settings: '[{"name": "ports", "type": "int", "value": 4000}, {"name": "constraints", "type": "string", "value": ["node.platform.os == linux"]}]'
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
    environment:
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
      - CSVTABLE_INPUT_PATH=${CSVTABLE_INPUT_PATH}
      - CSVTABLE_OUTPUT_PATH=${CSVTABLE_OUTPUT_PATH}
    ports:
      - '4000:4000'
