services:
  cc-rabbit-2d:
    build:
      args:
        APP_NAME: cc-rabbit-2d.py
      context: ./
      dockerfile: src/Dockerfile
      labels:
        io.simcore.authors: '{"authors": [{"name": "Odei Maiz", "email": "maiz@itis.swiss",
          "affiliation": "ITIS Foundation"}]}'
        io.simcore.contact: '{"contact": "maiz@itis.swiss"}'
        io.simcore.description: '{"description": "cc-rabbit-2d"}'
        io.simcore.inputs: '{"inputs": {"ECGs": {"label": "ECGs", "displayOrder":
          0, "description": "Computed ECGs out of a solver", "type": "data:*/*"},
          "y_1D": {"label": "action potentials", "displayOrder": 1, "description":
          "Action potentials out of solver", "type": "data:*/*"}}}'
        io.simcore.key: '{"key": "simcore/services/dynamic/cc-rabbit-2d"}'
        io.simcore.name: '{"name": "cc-rabbit-2d"}'
        io.simcore.outputs: '{"outputs": {"out_1": {"label": "ECG", "displayOrder":
          0, "description": "ECG csv", "type": "data:text/csv"}}}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.version: '{"version": "0.1.0"}'
        org.label-schema.build-date: ${BUILD_DATE}
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: ${VCS_REF}
        org.label-schema.vcs-url: https://github.com/ITISFoundation/osparc-services
      target: production
    image: ${DOCKER_REGISTRY}/cc-rabbit-2d:${DOCKER_IMAGE_TAG}
    volumes:
      - ./input:/home/jovyan/input
      - ./output:/home/jovyan/output
    ports:
    - 1241:8888
    init: true
version: '3.7'
