services:
  cc-rabbit-2d:
    build:
      args:
        APP_NAME: cc-rabbit-2d.py
      context: ./
      dockerfile: src/Dockerfile
      labels:
        io.simcore.authors: '{"authors": [{"name": "Odei Maiz", "email": "maiz@itis.swiss",
          "affiliation": "ITIS Foundation"}]}'
        io.simcore.contact: '{"contact": "maiz@itis.swiss"}'
        io.simcore.description: '{"description": "Graph viewer for data generated
          by Rabbit SS and Human GB 2D cardiac models"}'
        io.simcore.inputs: '{"inputs": {"ap": {"label": "APs", "displayOrder": 0,
          "description": "APs in a compressed zip file", "type": "data:*/zip", "fileToKeyMap":
          {"aps.zip": "ap"}}}}'
        io.simcore.key: '{"key": "simcore/services/dynamic/cc-2d-viewer"}'
        io.simcore.name: '{"name": "2D cardiac model viewer for Rabbit SS and Human
          GB"}'
        io.simcore.outputs: '{"outputs": {}}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.version: '{"version": "3.0.2"}'
        org.label-schema.build-date: ${BUILD_DATE}
        org.label-schema.schema-version: '1.0'
        org.label-schema.vcs-ref: ${VCS_REF}
        org.label-schema.vcs-url: https://github.com/ITISFoundation/osparc-services
        simcore.service.settings: '[ {"name": "ports", "type": "int", "value": 8888},
          {"name": "constraints", "type": "string", "value": ["node.platform.os ==
          linux"]} ]'
      target: production
    image: ${DOCKER_REGISTRY}/cc-2d-viewer:${DOCKER_IMAGE_TAG}
    init: true
    ports:
    - 1240:8888
    volumes:
    - ./validation/input:/home/jovyan/input
    - ./validation/output:/home/jovyan/output
version: '3.7'
