version: '3.6'
services:
  mapcore-widget:
    image: ${DOCKER_REGISTRY}/mapcore-widget:${DOCKER_IMAGE_TAG}
    build:
      context: ../../
      dockerfile: services/dy-mapcore-widget/Dockerfile
      target: production
      labels:
        io.simcore.key: '{"key": "simcore/services/dynamic/mapcore-widget"}'
        io.simcore.version: '{"version": "${DOCKER_IMAGE_TAG}"}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.name: '{"name": "Mapcore Flatmap"}'
        io.simcore.description: '{"description": "Interactive maps reveal the anatomy and functional relationships of the autonomic nerves and the organs that they innervate. 2D and 3D maps render spatial dynamics, connectivity, and physiology across a range of species and nerve-organ systems."}'
        io.simcore.authors: '{"authors": [{"name": "odeimaiz", "email": "maiz@itis.swiss", "affiliation": "ITIS Foundation"}]}'
        io.simcore.contact: '{"contact": "maiz@itis.swiss"}'
        io.simcore.inputs: '{"inputs": {}}'
        io.simcore.outputs: '{"outputs": {}}'
        simcore.service.settings: '[{"name": "resources", "type": "Resources", "value": {"mem_limit":17179869184, "cpu_limit": 4000000000}}, {"name": "ports", "type": "int", "value": 4000}, {"name": "constraints", "type": "string", "value": ["node.platform.os == linux"]}]'
        org.label-schema.schema-version: "1.0"
        org.label-schema.build-date: "${BUILD_DATE}"
        org.label-schema.vcs-url: "${VCS_URL}"
        org.label-schema.vcs-ref: "${VCS_REF}"
    environment:
      - SIMCORE_NODE_BASEPATH=${SIMCORE_NODE_BASEPATH}
      - MAPCOREWG_INPUT_PATH=${MAPCOREWG_INPUT_PATH}
      - MAPCOREWG_OUTPUT_PATH=${MAPCOREWG_OUTPUT_PATH}
    ports:
      - '4000:4000'
