services:
  3d-viewer:
    build:
      labels:
        io.simcore.authors:
          '{"authors": [{"name": "Sylvain Anderegg", "email": "anderegg@itis.swiss",
          "affiliation": "IT''IS Foundation"}]}'
        io.simcore.contact: '{"contact": "anderegg@itis.swiss"}'
        io.simcore.description: '{"description": "Paraview Web-based Visualizer"}'
        io.simcore.inputs:
          '{"inputs": {"A": {"displayOrder": 1, "label": "A", "description":
          "Any paraview compatible dataset. 1 dataset or N dataset compressed in a
          zip file.", "type": "data:*/*"}, "B": {"displayOrder": 1, "label": "B",
          "description": "Any paraview compatible dataset. 1 dataset or N dataset
          compressed in a zip file.", "type": "data:*/*"}}}'
        io.simcore.integration-version: '{"integration-version": "1.0.0"}'
        io.simcore.key: '{"key": "simcore/services/dynamic/3d-viewer"}'
        io.simcore.name: '{"name": "3d-viewer"}'
        io.simcore.outputs: '{"outputs": {}}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.version: '{"version": "3.0.3"}'
        org.label-schema.build-date: ${BUILD_DATE}
        org.label-schema.schema-version: "1.0"
        org.label-schema.vcs-ref: ${VCS_REF}
        org.label-schema.vcs-url: ${VCS_URL}
        simcore.service.bootsettings: "[]"
        simcore.service.reverse-proxy-settings: '{"strip_path":true}'
        simcore.service.settings:
          '[ {"name": "ports", "type": "int", "value": ${SERVER_PORT:-80}},
          {"name": "constraints", "type": "string", "value": ["node.platform.os ==
          linux"]}, {"name": "resources", "type": "resources", "value": { "Limits":
          { "NanoCPUs": 1000000000, "MemoryBytes": 4294967296 }, "Reservations":
          { "NanoCPUs": 1000000000, "MemoryBytes": 4294967296 } } } ]'
  3d-viewer-gpu:
    build:
      labels:
        io.simcore.authors:
          '{"authors": [{"name": "Sylvain Anderegg", "email": "anderegg@itis.swiss",
          "affiliation": "IT''IS Foundation"}]}'
        io.simcore.contact: '{"contact": "anderegg@itis.swiss"}'
        io.simcore.description: '{"description": "Paraview Web-based Visualizer"}'
        io.simcore.inputs:
          '{"inputs": {"A": {"displayOrder": 1, "label": "A", "description":
          "Any paraview compatible dataset. 1 dataset or N dataset compressed in a
          zip file.", "type": "data:*/*"}, "B": {"displayOrder": 1, "label": "B",
          "description": "Any paraview compatible dataset. 1 dataset or N dataset
          compressed in a zip file.", "type": "data:*/*"}}}'
        io.simcore.integration-version: '{"integration-version": "1.0.0"}'
        io.simcore.key: '{"key": "simcore/services/dynamic/3d-viewer-gpu"}'
        io.simcore.name: '{"name": "3d-viewer-gpu"}'
        io.simcore.outputs: '{"outputs": {}}'
        io.simcore.type: '{"type": "dynamic"}'
        io.simcore.version: '{"version": "3.0.3"}'
        org.label-schema.build-date: ${BUILD_DATE}
        org.label-schema.schema-version: "1.0"
        org.label-schema.vcs-ref: ${VCS_REF}
        org.label-schema.vcs-url: ${VCS_URL}
        simcore.service.bootsettings: "[]"
        simcore.service.reverse-proxy-settings: '{"strip_path":true}'
        simcore.service.settings:
          '[ {"name": "ports", "type": "int", "value": ${SERVER_PORT:-80}},
          {"name": "constraints", "type": "string", "value": [ "node.platform.os ==
          linux" ]}, {"name": "Resources", "type": "Resources", "value": { "Limits":
          { "NanoCPUs": 1000000000, "MemoryBytes": 4294967296 }, "Reservations":
          { "NanoCPUs": 1000000000, "MemoryBytes": 4294967296, "GenericResources": [
          { "DiscreteResourceSpec": { "Kind": "VRAM", "Value": 1 } } ] } } } ]'
version: "3.7"
